/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminWeeklyRouteImport } from './routes/_authenticated/admin/weekly'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/_authenticated/admin/submissions'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedAdminDailyLogsRouteImport } from './routes/_authenticated/admin/daily-logs'
import { Route as AuthenticatedAdminAdvisorRouteImport } from './routes/_authenticated/admin/advisor'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminWeeklyRoute =
  AuthenticatedAdminWeeklyRouteImport.update({
    id: '/weekly',
    path: '/weekly',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminDailyLogsRoute =
  AuthenticatedAdminDailyLogsRouteImport.update({
    id: '/daily-logs',
    path: '/daily-logs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdvisorRoute =
  AuthenticatedAdminAdvisorRouteImport.update({
    id: '/advisor',
    path: '/advisor',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/admin/advisor': typeof AuthenticatedAdminAdvisorRoute
  '/admin/daily-logs': typeof AuthenticatedAdminDailyLogsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/weekly': typeof AuthenticatedAdminWeeklyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/admin/advisor': typeof AuthenticatedAdminAdvisorRoute
  '/admin/daily-logs': typeof AuthenticatedAdminDailyLogsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/weekly': typeof AuthenticatedAdminWeeklyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/advisor': typeof AuthenticatedAdminAdvisorRoute
  '/_authenticated/admin/daily-logs': typeof AuthenticatedAdminDailyLogsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/_authenticated/admin/weekly': typeof AuthenticatedAdminWeeklyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/services'
    | '/admin/advisor'
    | '/admin/daily-logs'
    | '/admin/staff'
    | '/admin/submissions'
    | '/admin/weekly'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/services'
    | '/admin/advisor'
    | '/admin/daily-logs'
    | '/admin/staff'
    | '/admin/submissions'
    | '/admin/weekly'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/services'
    | '/_authenticated/admin'
    | '/_authenticated/admin/advisor'
    | '/_authenticated/admin/daily-logs'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/submissions'
    | '/_authenticated/admin/weekly'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/weekly': {
      id: '/_authenticated/admin/weekly'
      path: '/weekly'
      fullPath: '/admin/weekly'
      preLoaderRoute: typeof AuthenticatedAdminWeeklyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/submissions': {
      id: '/_authenticated/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/daily-logs': {
      id: '/_authenticated/admin/daily-logs'
      path: '/daily-logs'
      fullPath: '/admin/daily-logs'
      preLoaderRoute: typeof AuthenticatedAdminDailyLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/advisor': {
      id: '/_authenticated/admin/advisor'
      path: '/advisor'
      fullPath: '/admin/advisor'
      preLoaderRoute: typeof AuthenticatedAdminAdvisorRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdvisorRoute: typeof AuthenticatedAdminAdvisorRoute
  AuthenticatedAdminDailyLogsRoute: typeof AuthenticatedAdminDailyLogsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminWeeklyRoute: typeof AuthenticatedAdminWeeklyRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdvisorRoute: AuthenticatedAdminAdvisorRoute,
    AuthenticatedAdminDailyLogsRoute: AuthenticatedAdminDailyLogsRoute,
    AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
    AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
    AuthenticatedAdminWeeklyRoute: AuthenticatedAdminWeeklyRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
